[platformio]
default_envs = esp32-cyd
boards_dir = boards

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -D CORE_DEBUG_LEVEL=1

lib_deps =
    lvgl/lvgl@^8.3.11
    bblanchon/ArduinoJson@^7.0.4

[env:esp32-cyd]
board = esp32dev
board_build.partitions = min_spiffs.csv

build_flags =
    ${env.build_flags}
    -D BOARD_ESP32_CYD

lib_deps =
    ${env.lib_deps}
    lovyan03/LovyanGFX@^1.1.16
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git

[env:esp32-s3-jc3248w535]
board = esp32s3-jc3248w535

build_flags =
    ${env.build_flags}
    -D BOARD_JC3248W535EN
    -D BOARD_HAS_PSRAM

lib_deps =
    ${env.lib_deps}
    https://github.com/moononournation/Arduino_GFX.git#v1.4.9
